config/routes.rb
ListMaster::Application.routes.draw do
  devise_for :users

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  resources :lists do
    get 'dashboard'
  end
  match 'calendar' => 'lists#calendar', :as => :calendar
  resources :list_statuses
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'lists#dashboard'
  #root :to => 'lists#index'
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/list_statuses_controller.rb
class ListStatusesController < ApplicationController
  before_filter :authenticate_user!
    respond_to :html, :js

  def index
    @lists = List.get_all_lists_by_day_for_five_days(nil,nil)
  end

  def new
    @list_status = ListStatus.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: ListsDatatable.new(view_context) }
    end
  end

  def create
    params[:list_status][:date] = date_to_db(params[:list_status][:date])
    params[:list_ids].each do |id|
      list_status = ListStatus.create!(:list_id => id, :date => params[:list_status][:date], :status => params[:list_status][:status],
        :organization_id => params[:list_status][:organization_id], :created_by_user_id => current_user.id, :status => "checked_out" )
      if list_status.errors.present?
        flash[:error] = "Cannot add numbers. Please check your numbers and try again."
        render action: "new"  and return
      end
    end
    redirect_to lists_path, notice: "Successfully assigned packets to org."
  end
end

app/views/list_statuses/_datatables_js.html.erb
$(document).ready(function() {
  //* basic
  datatbles.dt_a();
});

//* datatables
datatbles = {
  dt_a: function() {
    $('#dt_a').dataTable({
              "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
              "sPaginationType": "bootstrap",
              "iDisplayLength": 25,
              "oLanguage": {
                  "sLengthMenu": "_MENU_ records per page"
              },
              "aoColumns": [
                { "bSortable": false },
                null,
                null,
                null,
                null,
                null,
                null,
                null
                ]
          });
  },
  dt_b: function() {
    var oTable = $('#dt_b').dataTable({
      "sDom": "<'row'<'span6'><'span6'f>r>",
      "sPaginationType": "bootstrap",
      "iDisplayLength": 500
    });
  }
};

app/views/list_statuses/new.html.erb
<div class="row-fluid">
  <%= form_for(@list_status,:html => { :class => "form_validation_ttip", :validate => true}) do |f| %>
  <div class="span8">
    <table class="table table-striped table-bordered dTableR" id="new-status" data-source="<%= new_list_status_url(format: "json") %>">
      <thead>
        <tr>
          <td></td>
          <td>List Name</td>
          <td>Turf</td>
          <td>Density</td>
          <td>Doors</td>
          <td><%= 2.days.ago.strftime("%m/%d") %></td>
          <td><%= 1.day.ago.strftime("%m/%d") %></td>
          <td class="today"><%= Time.zone.now.strftime("%m/%d") %></td>
          <td><%= 1.day.from_now.strftime("%m/%d") %></td>
          <td><%= 2.days.from_now.strftime("%m/%d") %></td>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
  </div>
  <div class="span3 form-sidebar">
    <ul>
      <li><input type="checkbox" id="selectall" name="selectall"> Select All Checkboxes</li>
      <li>&nbsp;</li>
      <li>Checkout date</li>
      <li><%= f.text_field :date, {:id => "dp1", :value => Time.zone.now.strftime("%m/%d/%Y"), :format => :display} %></li>
      <li></li>
      <li>Organization</li>
      <li><%= f.collection_select :organization_id, Organization.order(:id), :id, :organization_name, :prompt => true %></li>
      <li></li>
      <li><%= f.submit :submit, :class => 'btn btn-success' %></li>
    </ul>
  </div>
</div>
<div class="spacer">&nbsp;</div>
<% end %>