config/routes.rb
ListMaster::Application.routes.draw do
  devise_for :users

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  resources :lists do
    get 'dashboard'
  end
  match 'calendar' => 'lists#calendar', :as => :calendar
  resources :list_statuses
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'lists#dashboard'
  #root :to => 'lists#index'
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
  <title><%= content_for?(:title) ? yield(:title) : "ListMaster" %></title>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class='frontLayer'>
<header class="borBox row-fluid pat-lightwool">
  <div class="span2 pull-left">
    <%= link_to image_tag("logo.png"), root_url %>
  </div>
  <div class="span7 pull-left">
    <br/>
  </div>
  <div class="span3 pull-right">
    <% if user_signed_in? %>
    <div class="loginBox">
      <button class="btn btn-info droppy-toggle right" type='button' data-toggle='droppy'><i class='icon-white icon-user'></i> <%= current_user.full_name %>&nbsp;&nbsp;<b class='caret'></b></button>
      <ul class="dropdown-menu droppy-menu" id="uOpsL">
        <li><a href="#"><i class='icon-user'></i> Profile</a></li>
        <li><a href="#" data-target='settingsModal'><i class='icon-cog'></i> Settings</a></li>
        <li class='divider'></li>
        <li><%= link_to raw("<i class='icon-share-alt'></i> Log out"), destroy_user_session_path, {:method => "Delete"} %> </li>
        <li><a href="#" data-target='registerModal'><i class='icon-bookmark'></i> Register</a></li>
        <li class='divider'></li>
        <li><a href="#"><i class='icon-question-sign'></i> Help</a></li>
      </ul>
    </div>
    <% end %>
  </div>


</header>
<section class="subHead">
  <section class="row-fluid subHeadInner borBox">
    <div class='span12'>

      <h3 class='pull-left welcome'></h3>
      <div class='form-horizontal centerOnPage'><h3 class="welcome">Dashboard</h3></div>
      <ul class="bcrumbs pull-right">
      </ul>
    </div>
  </section>
</section>
<section class="container-fluid" id="mainContainer">
  <div class="row-fluid">
    <% if user_signed_in? %>
    <div class="span2 sideBar">
      <ul>
        <li data-link="home" class="active"><figure><i class='icon-home'></i> <div class='menuText'><%= link_to "Home", root_url %></div></figure></li>
        <li data-link="features"><figure><i class='icon-new-check'></i> <div class='menuText'><%= link_to "Assign Lists", new_list_status_path %></div></figure></li>
        <li data-link="calendar"><figure><i class='icon-calendar'></i> <div class='menuText'><%= link_to "Calendar", calendar_path %></div></figure></li>
        <hr/>
        <li data-link="none" class='dropper'>
          <figure><i class='icon-th'></i> <div class='menuText'>Manage&nbsp;›</div></figure>
          <ul class='subSide'>
            <li data-target='photos'><i class='icon-camera'></i> <div class='menuText'>Organizations</div></li>
            <li data-target='videos'><i class='icon-facetime-video'></i> <div class='menuText'>Packets</div></li>
            <li data-target='books'><i class='icon-book'></i> <div class='menuText'>Organizers</div></li>
          </ul>
        </li>
      </ul>
    </div>
    <% end %>
    <div class="span10 content borBox">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
</section>
<footer>
  <div class="container-fluid" id="footMain">
    <div class="row-fluid">
      <div class="span6">
        <div class="pull-left">
          <h6></h6>
        </div>
      </div>
      <div class="span6">
        <div class="pull-right">
          <h6>Obama for America</h6>
        </div>
      </div>
    </div>
  </div>
</footer>
</div>


 <!-- ##### MODALS #####- -->
<div class='modal fade hide' id="thisModal">

</div>

<!-- ### BACKGROUND DIV -->
<div class='bg'>
</div>
<%= javascript_include_tag "application" %>
<%= yield :scripts %>
</body>
</html>